/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifndef USE_HILDON
GtkWidget* create_winMain (void);
#endif
GtkWidget* create_papersizeDialog (void);
GtkWidget* create_aboutDialog (void);
GtkWidget* create_zoomDialog (void);
